openapi: 3.0.3
info:
  title: Шлюз API
  description: |
    Центральный маршрутизатор — принимает запросы от web-ui и перенаправляет
    на соответствующие микросервисы. Включает CORS, ограничение частоты запросов и предохранитель от отказов.
  version: 1.0.0
servers:
  - url: http://localhost:8080
    description: Локальная разработка
paths:
  /memory/{path}:
    get:
      tags: [Proxy → memory-service]
      summary: Проксирование на memory-service (с удалением /memory)
      parameters:
        - name: path
          in: path
          required: true
          schema:
            type: string
      responses:
        '200':
          description: Проксированный ответ от memory-service
        '429':
          $ref: '#/components/responses/RateLimited'
        '503':
          $ref: '#/components/responses/CircuitOpen'

  /tools/{path}:
    get:
      tags: [Proxy → tools-service]
      summary: Проксирование на tools-service (с удалением /tools)
      parameters:
        - name: path
          in: path
          required: true
          schema:
            type: string
      responses:
        '200':
          description: Проксированный ответ от tools-service
        '429':
          $ref: '#/components/responses/RateLimited'
        '503':
          $ref: '#/components/responses/CircuitOpen'

  /agents/{path}:
    get:
      tags: [Proxy → agent-service]
      summary: Проксирование на agent-service (с удалением /agents)
      parameters:
        - name: path
          in: path
          required: true
          schema:
            type: string
      responses:
        '200':
          description: Проксированный ответ от agent-service

  /chat:
    post:
      tags: [Proxy → agent-service]
      summary: Чат (без удаления префикса)
      responses:
        '200':
          description: Потоковый ответ (SSE)
        '429':
          $ref: '#/components/responses/RateLimited'

  /models:
    get:
      tags: [Proxy → agent-service]
      summary: Список моделей
      responses:
        '200':
          description: Проксированный ответ от agent-service

  /providers:
    get:
      tags: [Proxy → agent-service]
      summary: Провайдеры LLM
      responses:
        '200':
          description: Проксированный ответ от agent-service

  /workspaces:
    get:
      tags: [Proxy → agent-service]
      summary: Рабочие пространства
      responses:
        '200':
          description: Проксированный ответ от agent-service

  /health:
    get:
      tags: [Health]
      summary: Проверка здоровья (проксируется на memory-service)
      responses:
        '200':
          description: ОК
          content:
            application/json:
              schema:
                type: object
                properties:
                  status:
                    type: string

  /ydisk/{path}:
    get:
      tags: [Proxy → tools-service]
      summary: Яндекс.Диск (без удаления /ydisk)
      parameters:
        - name: path
          in: path
          required: true
          schema:
            type: string
      responses:
        '200':
          description: Проксированный ответ от tools-service

components:
  responses:
    RateLimited:
      description: Превышен лимит запросов
      content:
        application/json:
          schema:
            type: object
            properties:
              error:
                type: string
                example: превышен лимит запросов

    CircuitOpen:
      description: Сервис временно недоступен (предохранитель разомкнут)
      content:
        application/json:
          schema:
            type: object
            properties:
              error:
                type: string
                example: сервис недоступен
              reason:
                type: string
                example: предохранитель разомкнут
